name: zart
version: 1.3.0
description: Dart implementation of the Infocom Z-Machine.
homepage: https://atebitftw.github.io/site/
repository: https://github.com/atebitftw/zart
issue_tracker: https://github.com/atebitftw/zart/issues
platforms:
  web:
  windows:
  linux:
  macos:
  android:
  ios:
topics:
  - zmachine
  - z-compiler
  - z-interactive-fiction
  - interactive-fiction
executables:
  zart:
environment:
  sdk: 3.10.3
dependencies:
  logging: ^1.3.0
dev_dependencies:
  test: ^1.28.0
  lints: ^6.0.0