name: zart
version: 2.0.5+5
description: A Dart implementation of the Glulx (Inform 6 & 7) and Z-Machine interpreters, plus an abstraction layer so that apps use a single API to interact with both engines.
homepage: https://atebitftw.github.io/site/
repository: https://github.com/atebitftw/zart
issue_tracker: https://github.com/atebitftw/zart/issues
platforms:
  web:
  windows:
  linux:
  macos:
  android:
  ios:
topics:
  - zmachine
  - interactive-fiction
  - zork
environment:
  sdk: ^3.10.4
dependencies:
  logging: ^1.3.0
  args: ^2.7.0
dev_dependencies:
  test: ^1.28.0
  lints: ^6.0.0